
spring.application.name=backend

# Activate the 'dev' profile locally
spring.profiles.active=dev

# Database Connection (Safe to share the URL)
spring.datasource.url=jdbc:postgresql://localhost:5432/LockFoundDB

# JPA/Hibernate Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
logging.level.org.springdoc=DEBUG
logging.level.org.springframework.web=DEBUG